<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Shared\Nexora.Shared.csproj" />
    <ProjectReference Include="..\Nexora.Modules.Identity\Nexora.Modules.Identity.csproj" />
    <ProjectReference Include="..\Nexora.Modules.Workflow\Nexora.Modules.Workflow.csproj" />
    <ProjectReference Include="..\Nexora.Modules.Finance\Nexora.Modules.Finance.csproj" />
    <ProjectReference Include="..\Nexora.Modules.HR\Nexora.Modules.HR.csproj" />
  </ItemGroup>

</Project>
